[versions]
junit_version = "5+"

[libraries]
junit4 = {module = "junit:junit", version = "4+" }
mockito = {module = "org.mockito:mockito-core", version = "1+" }
assertj = {module = "org.assertj:assertj-core", version = "3.26+" }

[bundles]
testing = ["junit4", "mockito", "assertj"]

[plugins]

